name: beatthescore
title: Beat The Score
version: latest
base: core24
summary: Beat The Score music instrument learning game
description: |
  Beat The Score helps you learn your favorite music instrument with ease!

  This app supports loading Guitar Pro 5 files with file names "*.gp5",
  which can often be found for free on the internet. These can be placed
  in `~/snap/beatthescore/common/` for easy access. It then visualizes the
  session as either:

  - Piano Roll
  - Score
  - or Tablature

  Beat The Score gives you direct feedback about your accuracy of hitting notes and shows
  you your total score at the end. It also allows you to replay a session afterwards.
  There's also a "Training mode" that stops at every note so that you can slowly focus
  on playing your instrument right.

  Supported instrument types:

  - MIDI keyboards
  - Guitars through audio input analysis

  Note for systems using downstream kernels: Please ensure your kernel is built-with and providing ALSA MIDI via `/dev/snd/seq`.

  Copyright 2026 Alfred Neumayer, Felix Kugler, Daniel Novotny

  Released under the GNU GPLv2+.

confinement: strict
grade: stable
license: GPL-2.0-or-later
website: https://github.com/Beat-The-Score/BeatTheScore
donation: https://paypal.me/beidl

platforms:
  amd64:
  arm64:
  armhf:

apps:
  beatthescore:
    command: opt/BeatTheScore/bin/BeatTheScore
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/lomiri-launch
      - bin/default-scores
    plugs:
      - opengl
      - wayland
      - mir
      - x11
      - desktop
      - alsa
      - audio-record
      - audio-playback
      - maliit

plugs:
  lomiri-ui-toolkit:
    interface: content
    target: $SNAP/lomiri-ui-toolkit
    default-provider: lomiri-ui-toolkit-core24
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

layout:
  /usr/share/X11/xkb:
    symlink: $SNAP/lomiri-ui-toolkit/usr/share/X11/xkb
  /usr/share/icons:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /usr/share/alsa:
    symlink: $SNAP/lomiri-ui-toolkit/usr/share/alsa
  /etc/alsa:
    bind: $SNAP/lomiri-ui-toolkit/etc/alsa

parts:
  main:
    plugin: qmake
    source: .
    qmake-project-file: Diplomarbeit/Diplomarbeit.pro
    build-packages:
      - wget
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - qtmultimedia5-dev
      - libqt5svg5-dev
      - libqt5webkit5-dev
      - qtdeclarative5-private-dev
      - qtdeclarative5-dev-tools
      - intltool
      - libasound-dev
      - libssl-dev
    stage-packages:
      - qml-module-qtwebkit
    override-prime: |
      craftctl default
      mkdir -p ${CRAFT_PRIME}/bin
      cp -a /snap/lomiri-ui-toolkit-core24/current/command-chain/lomiri-launch ${CRAFT_PRIME}/bin/

  misc:
    after:
      - main
    plugin: dump
    source: snap/local
    prime:
      - bin/default-scores

  gpu-2404:
    after:
      - misc
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper

  cleanup:
    after:
      - gpu-2404
    plugin: nil
    build-snaps:
      - lomiri-ui-toolkit-core24
    override-prime: |
      craftctl default
      cd /snap/lomiri-ui-toolkit-core24/current
      find . -type f,l -exec rm -f ${CRAFT_PRIME}/{} \;
      rm -rf ${CRAFT_PRIME}/usr/share/doc
